# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

version: 2

# all dependencies are coalesced into this single group
# so that we get at most a single Dependabot PR per week
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)

updates:

- package-ecosystem: github-actions
  directory: /
  patterns: ["*"]
  multi-ecosystem-group: dependencies

- package-ecosystem: npm
  directory: /
  patterns: ["*"]
  multi-ecosystem-group: dependencies

- package-ecosystem: vcpkg
  directory: /
  patterns: ["*"]
  multi-ecosystem-group: dependencies

- package-ecosystem: pre-commit
  directory: /
  patterns: ["*"]
  multi-ecosystem-group: dependencies

- package-ecosystem: pip
  directory: /config
  patterns: ["*"]
  multi-ecosystem-group: dependencies

- package-ecosystem: docker
  directory: /config/lichess
  patterns: ["*"]
  multi-ecosystem-group: dependencies
