# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: build_and_test
description: Run build & tests via CDash client

inputs:
  cmake_preset:
    description: CMake preset to use
    required: true
  build_config:
    description: Build configuration
    required: true
  dashboard_type:
    description: CDash dashboard type to run
    required: true

runs:
  using: "composite"
  steps:
  - name: Install build dependencies
    uses: ./.github/actions/install-build-deps
    with:
      cmake_preset: ${{ inputs.cmake_preset }}

  - name: Install Python test dependencies
    shell: bash
    run: cmake -D "REPO_ROOT=${{ github.workspace }}" -P InstallPythonDeps.cmake
    working-directory: ${{ github.action_path }}

  - name: Configure CMake
    shell: bash
    env:
      BUILD_NAME: ${{ github.head_ref || github.ref_name }}.${{ runner.os }}.${{ inputs.cmake_preset }}.${{ inputs.build_config }}
      CMAKE_OSX_ARCHITECTURES: arm64;x86_64
    run: |
      cmake --preset ${{ inputs.cmake_preset }} -D BUILDNAME=${{ env.BUILD_NAME }} -D BENBOT_GUI=OFF --log-level=VERBOSE

  - name: Build and test
    shell: bash
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      CTEST_PARALLEL_LEVEL: '' # empty value to make ctest detect the number of cores
      CTEST_NO_TESTS_ACTION: error
      CTEST_OUTPUT_ON_FAILURE: 1
      JUNIT_FILENAME: junit-${{ runner.os }}-${{ inputs.cmake_preset }}-${{ inputs.build_config }}.xml
    run: |
      ctest -D ${{ inputs.dashboard_type }} -C ${{ inputs.build_config }} --schedule-random --output-junit ${{ env.JUNIT_FILENAME }} --timeout 300
    working-directory: ${{ github.workspace }}/Builds/${{ inputs.cmake_preset }}
    continue-on-error: true

  - name: Upload test results
    uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f   # v7
    with:
      name: junit-${{ runner.os }}-${{ inputs.cmake_preset }}-${{ inputs.build_config }}.xml
      path: ${{ github.workspace }}/Builds/${{ inputs.cmake_preset }}/junit-${{ runner.os }}-${{ inputs.cmake_preset }}-${{ inputs.build_config }}.xml

  - name: Run cmake install
    shell: bash
    if: inputs.build_config == 'Release'
    run: |
      cmake --install Builds/${{ inputs.cmake_preset }} --prefix deploy --component ben_bot --config Release

  - name: Upload artifact
    uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f   # v7
    if: inputs.build_config == 'Release'
    with:
      name: BenBot-${{ runner.os }}-${{ inputs.cmake_preset }}
      path: deploy   # using the full path here errors on Windows due to mixed forward/backslash usage in the path
      if-no-files-found: error
