# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

if (NOT TARGET Python::Interpreter)
    return ()
endif ()

check_python_modules_available (deps_available chess tqdm)

if (NOT deps_available)
    message (VERBOSE "matetrack dependencies not found, not adding these test cases")
    return ()
endif ()

FetchContent_Declare (
    matetrack
    SYSTEM
    GIT_REPOSITORY "https://github.com/vondele/matetrack.git"
    GIT_TAG origin/master
    OVERRIDE_FIND_PACKAGE
)

FetchContent_MakeAvailable (matetrack)

# cmake-format: off
add_test (
    NAME ben_bot.matetrack
    COMMAND Python::Interpreter matecheck.py
        --engine "$<TARGET_FILE:ben_bot>"
        --epdFile mates2000.epd
        --nodes 10000
        --depth 10
        --time 30
        --showAllIssues --showAllStats --bench
    WORKING_DIRECTORY "${matetrack_SOURCE_DIR}"
)
# cmake-format: on

set_tests_properties (
    ben_bot.matetrack PROPERTIES FAIL_REGULAR_EXPRESSION "the following issues were detected:"
)
