# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

check_python_modules_available (deps_available chess tqdm)

add_feature_info (benbot_matetrack_testing deps_available "BenBot matetrack testing")

if (NOT deps_available)
    return ()
endif ()

FetchContent_Declare (
    matetrack
    SYSTEM
    GIT_REPOSITORY "https://github.com/vondele/matetrack.git"
    GIT_TAG origin/master
    OVERRIDE_FIND_PACKAGE
)

FetchContent_MakeAvailable (matetrack)

add_test (
    NAME ben_bot.matetrack
    COMMAND Python::Interpreter matecheck.py --engine "$<TARGET_FILE:ben_bot>" --epdFile
            mates2000.epd --nodes 10000 --depth 10 --time 30 --showAllIssues --showAllStats --bench
    WORKING_DIRECTORY "${matetrack_SOURCE_DIR}"
)

set_property (
    TEST ben_bot.matetrack APPEND
    PROPERTY FAIL_REGULAR_EXPRESSION "the following issues were detected:"
             "Exception parsing pv from info:"
)
