# ======================================================================================
#
# libchess - a chess engine by Ben Vining
#
# ======================================================================================

# config file for relint: https://github.com/codingjoe/relint
# a regex-based text file linter that can check for various tokens/patterns
# this tool is run by pre-commit, but only on-demand, not as a regular hook
# to run it, use: just relint

- name: todo
  pattern: '(?i)todo'
  hint: TODO notes found
  filePattern: .*\.(cpp|hpp|cmake)

- name: if 0
  pattern: '#[ ]*if 0'
  hint: \#if 0 found
  filePattern: .*\.(cpp|hpp)
