# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: create_release
description: Create a GitHub release

inputs:
  tag_name:
    description: Git tag name
    required: true

runs:
  using: "composite"
  steps:
  - name: Write release notes
    shell: bash
    run: |
      python3 ${{ github.action_path }}/WriteReleaseNotes.py CHANGELOG.md release-notes.md

  - name: Download artifacts
    id: download
    uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c   # v8
    with:
      path: artifacts

  - name: Re-zip artifacts
    shell: bash
    run: |
      python3 ${{ github.action_path }}/ReZipArtifacts.py ${{ steps.download.outputs.download-path }} rezipped

  - name: Create release
    uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe   # v2
    with:
      tag_name: ${{ inputs.tag_name }}
      files: rezipped/**
      fail_on_unmatched_files: true
      generate_release_notes: true   # autogenerate the link to the version range diff
      body_path: release-notes.md   # body will the appended to autogenerated content
      make_latest: true
