# ======================================================================================
#
# libchess - a chess engine by Ben Vining
#
# ======================================================================================

include_guard (GLOBAL)

# general options
set (DOXYGEN_PREDEFINED DOXYGEN=1)
set (DOXYGEN_EXTRACT_ALL YES)
set (DOXYGEN_MULTILINE_CPP_IS_BRIEF YES)
set (DOXYGEN_ALWAYS_DETAILED_SEC YES)
set (DOXYGEN_DISTRIBUTE_GROUP_DOC YES)
set (DOXYGEN_SOURCE_BROWSER YES)
set (DOXYGEN_GENERATE_TREEVIEW YES)
set (DOXYGEN_BUILTIN_STL_SUPPORT YES)
set (DOXYGEN_GROUP_NESTED_COMPOUNDS YES)
set (DOXYGEN_DISABLE_INDEX NO)
set (DOXYGEN_EXTERNAL_PAGES NO)
set (DOXYGEN_EXTRACT_PRIV_VIRTUAL YES)
set (DOXYGEN_GENERATE_XML YES)
set (DOXYGEN_HIDE_FRIEND_COMPOUNDS YES)
set (DOXYGEN_INLINE_INHERITED_MEMB YES)
set (DOXYGEN_NUM_PROC_THREADS 0) # value 0 means Doxygen will use all available cores
set (DOXYGEN_SHOW_HEADERFILE NO)
set (DOXYGEN_SORT_GROUP_NAMES YES)
set (DOXYGEN_SORT_MEMBERS_CTORS_1ST YES)
set (DOXYGEN_TEMPLATE_RELATIONS YES)
set (DOXYGEN_TIMESTAMP DATE)

# dot
set (DOXYGEN_DOT_IMAGE_FORMAT svg)
set (DOXYGEN_DOT_TRANSPARENT YES)
set (DOXYGEN_DOT_MULTI_TARGETS YES)
set (DOXYGEN_INTERACTIVE_SVG YES)
set (DOXYGEN_DOT_GRAPH_MAX_NODES 75)

# HTML
set (DOXYGEN_EXT_LINKS_IN_WINDOW YES)
set (DOXYGEN_HTML_FORMULA_FORMAT svg)
set (DOXYGEN_USE_MATHJAX YES)
set (DOXYGEN_HTML_DYNAMIC_SECTIONS YES)
