# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Build & test (internal)

on:
  workflow_call:
    inputs:
      dashboard_type:
        description: Type of CTest dashboard to run (Nightly, Experimental, or Continuous)
        type: string # for some reason, workflow_call doesn't support choice inputs
        required: true

run-name: Build & test (${{ inputs.dashboard_type }})

defaults:
  run:
    shell: bash

jobs:

  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
        config: [Debug, Release]
        preset: [clang]
        include:
        - os: windows-latest
          preset: msvc
          config: Debug
        - os: windows-latest
          preset: msvc
          config: Release
        - os: ubuntu-latest
          preset: gcc
          config: Debug
        - os: ubuntu-latest
          preset: gcc
          config: Release
        - os: ubuntu-latest
          preset: clang-asan
          config: Debug
        - os: ubuntu-latest
          preset: clang-ubsan
          config: Debug
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}.${{ matrix.preset }}.${{ matrix.config }}.${{ inputs.dashboard_type }}
    permissions:
      contents: read
    timeout-minutes: 180 # 3 hours
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      CTEST_PARALLEL_LEVEL: '' # empty value to make ctest detect the number of cores
      CTEST_NO_TESTS_ACTION: error
      CTEST_OUTPUT_ON_FAILURE: 1
      JUNIT_FILENAME: junit-${{ matrix.os }}-${{ matrix.preset }}-${{ matrix.config }}.xml
      # NB. Windows runners may error out if we make these absolute paths prefixed with
      # ${{ github.workspace }}, because that may contain Windows-style backslashes
      BUILD_DIR: Builds/${{ matrix.preset }}
      DEPLOY_DIR: deploy

    steps:
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libc++-dev libc++abi-dev

    - name: Ensure CMake 4.0
      uses: lukka/get-cmake@v4.2.3

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Python dependencies
      run: cmake -P InstallPythonDeps.cmake
      working-directory: .github/scripts

    - name: Configure CMake
      env:
        BUILD_NAME: ${{ github.head_ref || github.ref_name }}.${{ matrix.os }}.${{ matrix.preset }}.${{ matrix.config }}
        CMAKE_OSX_ARCHITECTURES: arm64;x86_64
      run: cmake --preset ${{ matrix.preset }} -D BENBOT_DOCS=OFF -D BUILDNAME=${{ env.BUILD_NAME }}

    - name: Build and test
      run: ctest -D ${{ inputs.dashboard_type }} -C ${{ matrix.config }} --schedule-random --output-junit ${{ env.JUNIT_FILENAME }}
      working-directory: ${{ env.BUILD_DIR }}
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.JUNIT_FILENAME }}
        path: ${{ env.BUILD_DIR }}/${{ env.JUNIT_FILENAME }}

    - name: Run cmake install
      if: matrix.config == 'Release'
      run: cmake --install ${{ env.BUILD_DIR }} --prefix ${{ env.DEPLOY_DIR }} --component ben_bot --config ${{ matrix.config }}

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      if: matrix.config == 'Release'
      with:
        name: BenBot-${{ matrix.os }}-${{ matrix.preset }}
        path: deploy # using the full path here errors on Windows due to mixed forward/backslash usage in the path
        if-no-files-found: error

  report_aggregate_test_results:
    runs-on: ubuntu-latest
    name: Report aggregate test results
    timeout-minutes: 10
    needs: build_and_test
    permissions:
      checks: write
      pull-requests: write

    steps:
    - name: Download JUnit results
      uses: actions/download-artifact@v7
      with:
        path: junit
        pattern: junit-*
        merge-multiple: true

    - name: Report aggregate results
      uses: EnricoMi/publish-unit-test-result-action@v2.23.0
      with:
        check_name: "Test Results (${{ github.event.workflow_run.event || github.event_name }})"
        files: junit/*.xml
        comment_mode: changes in failures
        large_files: true
        report_individual_runs: true
