# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Build GUI

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  build_gui:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025-vs2026, macos-15]
        preset: [clang]
        include:
        - os: windows-2025-vs2026
          preset: msvc
        - os: ubuntu-latest
          preset: gcc
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}.${{ matrix.preset }}
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10     # v6

    - name: Install Inkscape (MacOS)
      if: runner.os == 'macOS'
      run: brew install --cask inkscape

    - name: Install Inkscape & ImageMagick (Windows)
      if: runner.os == 'Windows'
      run: choco install -y inkscape imagemagick

    - name: Install Vulkan SDK
      if: runner.os != 'macOS'
      uses: humbletim/install-vulkan-sdk@30ba978f977e81b72d091fc8888feb1fb26f9aff # v1.2
      with:
        cache: true

    - name: Install gtk (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev

    - name: Build
      uses: ./.github/actions/run_build
      with:
        cmake_preset: ${{ matrix.preset }}
        build_target: benbot_gui
        build_gui: ON

      # TODO: upload artifacts
