# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Build GUI

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  build_gui:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025-vs2026, macos-15]
        config: [Debug, Release]
        preset: [clang]
        include:
        - os: windows-2025-vs2026
          preset: msvc
          config: Debug
        - os: windows-2025-vs2026
          preset: msvc
          config: Release
        - os: ubuntu-latest
          preset: gcc
          config: Debug
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}.${{ matrix.preset }}.${{ matrix.config }}
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd     # v6

    - name: Build
      uses: ./.github/actions/run_build
      with:
        cmake_preset: ${{ matrix.preset }}
        build_config: ${{ matrix.config }}
        build_target: benbot_gui
        build_gui: ON

      # TODO: upload artifacts
