# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Deploy Lichess

run-name: Deploy Lichess

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Git tag to checkout
        type: string
        required: true
  workflow_call:
    inputs:
      tag_name:
        description: Git tag to checkout
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}.${{ inputs.tag_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  build_docker:
    runs-on: ubuntu-latest
    name: Update lichess-bot Docker image
    timeout-minutes: 20
    environment:
      name: lichess-bot-image
      url: ${{ steps.print_url.outputs.url }}
    env:
      LOCAL_TAG: benbot:${{ inputs.tag_name }}
      REMOTE_TAG: benvining/benbot-lichess:${{ inputs.tag_name }}

    steps:
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: benvining
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v5
#      with:
#        ref: ${{ inputs.tag_name }}

    - name: Configure config file
      run: python3 SetupLichessConfig.py ${{ github.workspace }}/lichess/config.yml ${{ secrets.LICHESS_TOKEN }} ${{ inputs.tag_name }}
      working-directory: .github/scripts

    - name: Run Docker build
      run: docker build --file lichess/Dockerfile --tag ${{ env.LOCAL_TAG }} .

    - name: Tag image
      run: docker tag ${{ env.LOCAL_TAG }} ${{ env.REMOTE_TAG }}

    - name: Push to Docker hub
      run: docker push ${{ env.REMOTE_TAG }}

    - name: Print Docker tag URL
      id: print_url
      run: python3 PrintDockerTagURL.py ${{ inputs.tag_name }} >> $GITHUB_OUTPUT
      working-directory: .github/scripts
