# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_call:
    inputs:
      ref:
        # this is needed because this workflow is used via workflow_call in the tag & release action
        # after the version has been bumped, at which point the default for actions/checkout would be
        # the old version (the ref that triggered the action), and we want the deployed docs to display
        # the most recent version
        description: Git tag to checkout
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    name: Build docs
    timeout-minutes: 10
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      BUILD_DIR: ${{ github.workspace }}/Builds/clang
      DEPLOY_DIR: ${{ github.workspace }}/deploy

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y doxygen graphviz libc++-dev libc++abi-dev

    - name: Checkout code
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.ref || github.ref }}

    - name: Configure CMake
      run: cmake --preset clang -D BENBOT_TESTS=OFF

    - name: Build docs
      run: cmake --build . --target ben_bot_docs
      working-directory: ${{ env.BUILD_DIR }}

    - name: Report Doxygen warnings
      if: always()
      run: |
        cmake -E echo "# Doxygen warnings" >> $GITHUB_STEP_SUMMARY
        cmake -E cat logs/Doxygen.log >> $GITHUB_STEP_SUMMARY

    - name: Run CMake install
      run: cmake --install . --prefix ${{ env.DEPLOY_DIR }} --component ben_bot_docs
      working-directory: ${{ env.BUILD_DIR }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        name: BenBot-docs
        path: ${{ env.DEPLOY_DIR }}/share/doc/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: BenBot-docs
