# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:
    inputs:
      ref:
        # this is needed because this workflow is used via workflow_call in the tag & release action
        # after the version has been bumped, at which point the default for actions/checkout would be
        # the old version (the ref that triggered the action), and we want the deployed docs to display
        # the most recent version
        description: Git tag to checkout
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    name: Build docs
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
    env:
      CMAKE_PRESET: gcc
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      BUILD_DIR: ${{ github.workspace }}/Builds/gcc
      DEPLOY_DIR: ${{ github.workspace }}/deploy

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y doxygen graphviz

    - name: Ensure CMake 4.0
      uses: lukka/get-cmake@f176ccd3f28bda569c43aae4894f06b2435a3375 # v4.2.3

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ inputs.ref || github.ref }}

    - name: Configure CMake
      run: cmake --preset ${{ env.CMAKE_PRESET }} -D BENBOT_TESTS=OFF

    - name: Build docs
      run: cmake --build . --target ben_bot_docs
      working-directory: ${{ env.BUILD_DIR }}

    # Parse Doxygen warnings to create JSON data for check status
    - name: Produce summary for check
      if: always()
      id: parse_doxygen_warnings
      env:
        SCRIPT: ${{ github.workspace }}/.github/scripts/ReportDoxygenWarnings.py
        DOXYGEN_LOG: ${{ github.workspace }}/logs/Doxygen.log
      run: |
        summary="$(python3 ${{ env.SCRIPT }}  --summary --doxygen-log=${{ env.DOXYGEN_LOG }})"
        echo "summary=$summary" >> "$GITHUB_OUTPUT"
        annotations="$(python3 ${{ env.SCRIPT }} --doxygen-log=${{ env.DOXYGEN_LOG }} --repo-root ${{ github.workspace }})"
        echo "annotations=$annotations" >> "$GITHUB_OUTPUT"

    # Create status check to report warnings
    - name: Report check state
      if: always()
      uses: LouisBrunner/checks-action@6b626ffbad7cc56fd58627f774b9067e6118af23 # v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Docs warnings
        conclusion: ${{ job.status }} # expands to failure if any step has failed, success otherwise
        output: ${{ steps.parse_doxygen_warnings.outputs.summary }}
        annotations: ${{ steps.parse_doxygen_warnings.outputs.annotations }}

    - name: Run CMake install
      run: |
        cmake --install ${{ env.BUILD_DIR }} --prefix ${{ env.DEPLOY_DIR }} --component ben_bot_docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
      with:
        name: BenBot-docs
        path: ${{ env.DEPLOY_DIR }}/share/doc/html

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Deploy docs
    timeout-minutes: 5
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
      with:
        artifact_name: BenBot-docs
