# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: SPRT

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  sprt:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    name: Run SPRT test
    timeout-minutes: 60
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      BUILD_DIR: Builds/clang
      SPRT_OUTPUT_LOG: ${{ github.workspace }}/logs/sprt/output.log

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Download fastchess release
      id: download_fastchess
      uses: robinraju/release-downloader@v1.12
      with:
        repository: Disservin/fastchess
        latest: true
        preRelease: true
        fileName: '*-ubuntu-*'
        tarBall: false
        zipBall: false
        out-file-path: fastchess
        extract: true

    - name: Print fastchess filename
      id: fastchess_filename
      run: |
        zip_path=${{ fromJson(steps.download_fastchess.outputs.downloaded_files)[0] }}
        filename=$(basename "$zip_path" ".zip")
        dirpath=$(dirname "$zip_path")
        result="$dirpath/$filename"
        echo "fastchess=$result" >> "$GITHUB_OUTPUT"

    - name: Download latest BenBot release
      id: download_benbot
      uses: robinraju/release-downloader@v1.12
      with:
        latest: true
        fileName: BenBot-ubuntu-latest-clang.zip
        tarBall: false
        zipBall: false
        out-file-path: baseline
        extract: true

    - name: Print BenBot filename
      id: benbot_filename
      run: |
        zip_path=${{ fromJson(steps.download_benbot.outputs.downloaded_files)[0] }}
        filename=$(basename "$zip_path" ".zip")
        dirpath=$(dirname "$zip_path")
        result="$dirpath/$filename/bin/ben_bot"
        echo "benbot=$result" >> "$GITHUB_OUTPUT"

    - name: Add execution permissions
      run: chmod --preserve-root 777 ${{ steps.fastchess_filename.outputs.fastchess }} ${{ steps.benbot_filename.outputs.benbot }}

    - name: Configure CMake
      run: cmake --preset clang -D BENBOT_DOCS=OFF -D FASTCHESS_PROGRAM=${{ steps.fastchess_filename.outputs.fastchess }}

    - name: Inject baseline binary
      run: cmake -D BASELINE_BINARY=${{ steps.benbot_filename.outputs.benbot }} -P ${{ env.BUILD_DIR }}/InjectSPRTBaseline-Release.cmake

    - name: Build
      run: cmake --build . --target ben_bot --config Release
      working-directory: ${{ env.BUILD_DIR }}

    - name: Run SPRT test
      run: |
        cmake -E make_directory ${{ github.workspace }}/logs/sprt
        cmake --build . --target sprt --config Release | tee ${{ env.SPRT_OUTPUT_LOG }}
      working-directory: ${{ env.BUILD_DIR }}

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: sprt-logs
        path: logs/sprt
        if-no-files-found: error

    - name: Report results
      if: always()
      run: python3 ReportSPRTResults.py ${{ env.SPRT_OUTPUT_LOG }} >> $GITHUB_STEP_SUMMARY
      working-directory: .github/scripts
