# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: SPRT

run-name: Run SPRT test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  sprt:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    name: Run SPRT test
    timeout-minutes: 60
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      BUILD_DIR: Builds/clang
      FASTCHESS_PATH: fastchess/fastchess-ubuntu-22.04
      BASELINE_PATH: baseline/ben_bot-1.3.0-Linux-Clang

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Download fastchess release
      uses: robinraju/release-downloader@v1.12
      with:
        repository: Disservin/fastchess
        latest: true
        preRelease: true
        fileName: '*-ubuntu-*'
        tarBall: false
        zipBall: false
        out-file-path: fastchess
        extract: true

    - name: Download latest BenBot release
      uses: robinraju/release-downloader@v1.12
      with:
        latest: true
        fileName: '*-Linux-Clang'
        tarBall: false
        zipBall: false
        out-file-path: baseline

    - name: Add execution permissions
      run: chmod --preserve-root 777 ${{ env.FASTCHESS_PATH }} ${{ env.BASELINE_PATH }}

    - name: Configure CMake
      run: cmake --preset clang -D BENBOT_DOCS=OFF -D FASTCHESS_PROGRAM=${{ env.FASTCHESS_PATH }}

    - name: Inject baseline binary
      run: cmake -D BASELINE_BINARY=${{ env.BASELINE_PATH }} -P ${{ env.BUILD_DIR }}/InjectSPRTBaseline-Release.cmake

    - name: Build
      run: cmake --build . --target ben_bot --config Release
      working-directory: ${{ env.BUILD_DIR }}

    - name: Run SPRT test
      run: cmake --build . --target sprt --config Release
      working-directory: ${{ env.BUILD_DIR }}
