# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Bump version, create tag & release

on:
  workflow_dispatch:
    inputs:
      version_part:
        description: "Version part to bump"
        required: true
        type: choice
        options:
        - 'major'
        - 'minor'
        - 'patch'

run-name: Bump version (${{ inputs.version_part }})

concurrency:
  group: ${{ github.workflow }}

defaults:
  run:
    shell: bash

jobs:

  # updates the version in all repo files, creates a git tag & pushes to Github
  # this step also outputs the tag name
  # note that the default for actions/checkout is to use the ref that triggered the action,
  # meaning that in order to use the version created by this step, subsequent steps need to
  # depend on this step in their needs: field and specify:
  #   with:
  #     ref: ${{ needs.bump_version.outputs.tag_name }}
  bump_version:
    runs-on: ubuntu-latest
    name: Bump version & create tag
    timeout-minutes: 10
    environment:
      name: bump-project-version
      url: ${{ steps.bump_version.outputs.tag_url }}
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0

    - uses: ./.github/actions/bump_version
      id: bump_version
      with:
        version_part: ${{ inputs.version_part }}
        gpg_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

    outputs:
      tag_name: ${{ steps.bump_version.outputs.git_tag }}

  # builds & uploads just release binaries on all supported platforms
  build:
    needs: bump_version
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-2025-vs2026, macos-15]
        preset: [clang]
        include:
        - os: windows-2025-vs2026
          preset: msvc
        - os: ubuntu-latest
          preset: gcc
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }}.${{ matrix.preset }})
    timeout-minutes: 10
    permissions:
      contents: read
    environment:
      name: codesigning
      url: https://github.com/benthevining/BenBot/releases/tag/${{ needs.bump_version.outputs.tag_name }}

    steps:
    - name: Import signing certificate to keychain
      if: runner.os == 'macOS'
      uses: Apple-Actions/import-codesign-certs@fe74d46e82474f87e1ba79832ad28a4013d0e33a # v6.1.0
      with:
        p12-file-base64: ${{ secrets.CODESIGN_CERT_FILE_BASE64 }}
        p12-password: ${{ secrets.CODESIGN_CERT_PASSWORD }}

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ needs.bump_version.outputs.tag_name }}

    - uses: ./.github/actions/run_build
      id: run_build
      with:
        cmake_preset: ${{ matrix.preset }}
        extra_config_args: -D "BENBOT_CODESIGN_ID=${{ secrets.BENBOT_CODESIGN_ID }}" -D BUILD_TESTING=OFF

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: BenBot-${{ matrix.os }}-${{ matrix.preset }}
        path: ${{ steps.run_build.outputs.deploy_dir }}
        if-no-files-found: error

  # build & deploy docs from new tag
  build_docs:
    needs: bump_version
    permissions:
      contents: read
      checks: write
      pages: write
      id-token: write
    uses: ./.github/workflows/docs.yml
    with:
      ref: ${{ needs.bump_version.outputs.tag_name }}

  # creates a Github release with the build & docs artifacts
  # the release notes are populated from the changelog file (which was generated by the bump-my-version command)
  create_release:
    needs: [bump_version, build, build_docs]
    runs-on: ubuntu-latest
    name: Create GitHub release
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ needs.bump_version.outputs.tag_name }}

    - uses: ./.github/actions/create_release
      with:
        tag_name: ${{ needs.bump_version.outputs.tag_name }}

  # builds the lichess-bot Docker image from the latest git tag & uploads it to Dockerhub
  build_docker:
    needs: bump_version
    runs-on: ubuntu-latest
    name: Update lichess-bot Docker image
    timeout-minutes: 20
    permissions:
      contents: read
    environment:
      name: lichess-bot-image
      url: ${{ steps.build_docker.outputs.url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6
      with:
        ref: ${{ needs.bump_version.outputs.tag_name }}

    - uses: ./.github/actions/build_docker
      id: build_docker
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        lichess_token: ${{ secrets.LICHESS_TOKEN }}
        tag_name: ${{ needs.bump_version.outputs.tag_name }}

  # stops the old Docker container, pulls the newly built image at the latest tag from Dockerhub,
  # and starts new container from this image
  deploy_vps:
    needs: [bump_version, build_docker]
    runs-on: ubuntu-latest
    name: Deploy Docker image to VPS
    timeout-minutes: 10
    permissions: {} # no permissions needed
    environment:
      name: vps
      url: https://cloud.digitalocean.com/droplets/517152619
    env:
      REMOTE_TAG: benvining/benbot-lichess:${{ needs.bump_version.outputs.tag_name }}
      IMAGE_NAME: benbot

    steps:
    - name: Update & restart Docker image
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1
      with:
        host: ${{ secrets.VPS_IP_V4 }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker stop ${{ env.IMAGE_NAME }}
          docker rm ${{ env.IMAGE_NAME }}
          docker pull ${{ env.REMOTE_TAG }}
          docker run -d --name ${{ env.IMAGE_NAME }} ${{ env.REMOTE_TAG }}
          docker image prune -a -f
