# ======================================================================================
#
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓███████▓▒░       ░▒▓███████▓▒░ ░▒▓██████▓▒░▒▓████████▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓██████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░
# ░▒▓███████▓▒░░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓███████▓▒░ ░▒▓██████▓▒░  ░▒▓█▓▒░
#
# ======================================================================================

name: Bump version, create tag & release

on:
  workflow_dispatch:
    inputs:
      version_part:
        description: "Version part to bump"
        required: true
        type: choice
        options:
        - 'major'
        - 'minor'
        - 'patch'

run-name: Bump version (${{ inputs.version_part }})

concurrency:
  group: ${{ github.workflow }}

defaults:
  run:
    shell: bash

jobs:

  # updates the version in all repo files, creates a git tag & pushes to Github
  # this step also outputs the tag name
  # note that the default for actions/checkout is to use the ref that triggered the action,
  # meaning that in order to use the version created by this step, subsequent steps need to
  # depend on this step in their needs: field and specify:
  #   with:
  #     ref: ${{ needs.bump_version.outputs.tag_name }}
  bump_version:
    runs-on: ubuntu-latest
    name: Bump version & create tag
    timeout-minutes: 10
    environment:
      name: bump-project-version
      url: ${{ steps.bump_version.outputs.tag_url }}
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0

    - uses: ./.github/actions/bump_version
      id: bump_version
      with:
        version_part: ${{ inputs.version_part }}
        gpg_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

    outputs:
      tag_name: ${{ steps.bump_version.outputs.git_tag }}

  # builds & uploads just release binaries on all supported platforms
  build:
    needs: bump_version
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-2025-vs2026, macos-15]
        preset: [clang]
        include:
        - os: windows-2025-vs2026
          preset: msvc
        - os: ubuntu-latest
          preset: gcc
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }}.${{ matrix.preset }})
    timeout-minutes: 10
    permissions:
      contents: read
    environment:
      name: codesigning
      url: https://github.com/benthevining/BenBot/releases/tag/${{ needs.bump_version.outputs.tag_name }}
    env:
      CMAKE_OSX_ARCHITECTURES: arm64;x86_64
      CMAKE_BUILD_PARALLEL_LEVEL: 8
      # NB. Windows runners may error out if we make these absolute paths prefixed with
      # ${{ github.workspace }}, because that may contain Windows-style backslashes
      BUILD_DIR: Builds/${{ matrix.preset }}
      DEPLOY_DIR: deploy

    steps:
    - name: Install libc++
      if: runner.os == 'Linux' && matrix.preset == 'clang'
      run: |
        sudo apt-get update
        sudo apt-get install -y libc++-dev libc++abi-dev

    - name: Install Clang21
      if: runner.os == 'Linux' && matrix.preset == 'clang'
      uses: aminya/setup-cpp@1f17f92d6a52bfcb1a25348e2c526c2e5cbb1134 # v1.8.0
      with:
        llvm: 21
        clang: 21

    - name: Install CMake 4.0
      uses: lukka/get-cmake@ea83089aa35e08e459464341fe24ad024ee2466f # v4.3.1

    - name: Import signing certificate to keychain
      if: runner.os == 'macOS'
      uses: Apple-Actions/import-codesign-certs@fe74d46e82474f87e1ba79832ad28a4013d0e33a # v6.1.0
      with:
        p12-file-base64: ${{ secrets.CODESIGN_CERT_FILE_BASE64 }}
        p12-password: ${{ secrets.CODESIGN_CERT_PASSWORD }}

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ needs.bump_version.outputs.tag_name }}

    - name: Configure CMake
      run: |
        cmake --preset ${{ matrix.preset }} -D "BENBOT_CODESIGN_ID=${{ secrets.BENBOT_CODESIGN_ID }}" -D BENBOT_DOCS=OFF -D BENBOT_TESTS=OFF

    - name: Build
      run: cmake --build . --config Release --target ben_bot
      working-directory: ${{ env.BUILD_DIR }}

    - name: Run cmake install
      run: |
        cmake --install ${{ env.BUILD_DIR }} --prefix ${{ env.DEPLOY_DIR }} --component ben_bot --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: BenBot-${{ matrix.os }}-${{ matrix.preset }}
        path: ${{ env.DEPLOY_DIR }}
        if-no-files-found: error

  # build & deploy docs from new tag
  build_docs:
    needs: bump_version
    permissions:
      contents: read
      checks: write
      pages: write
      id-token: write
    uses: ./.github/workflows/docs.yml
    with:
      ref: ${{ needs.bump_version.outputs.tag_name }}

  # creates a Github release with the build & docs artifacts
  # the release notes are populated from the changelog file (which was generated by the bump-my-version command)
  create_release:
    needs: [bump_version, build, build_docs]
    runs-on: ubuntu-latest
    name: Create GitHub release
    timeout-minutes: 10
    permissions:
      contents: write
    env:
      RELEASE_NOTES_FILE: ${{ github.workspace }}/release-notes.md
      REZIPPED_ARTIFACTS: ${{ github.workspace }}/rezipped

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ needs.bump_version.outputs.tag_name }}

    - name: Write release notes
      run: python3 WriteReleaseNotes.py ${{ github.workspace }}/CHANGELOG.md ${{ env.RELEASE_NOTES_FILE }}
      working-directory: .github/scripts

    - name: Download artifacts
      id: download
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        path: artifacts

    - name: Re-zip artifacts
      run: python3 ReZipArtifacts.py ${{ steps.download.outputs.download-path }} ${{ env.REZIPPED_ARTIFACTS }}
      working-directory: .github/scripts

    - name: Create release
      uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
      with:
        tag_name: ${{ needs.bump_version.outputs.tag_name }}
        files: ${{ env.REZIPPED_ARTIFACTS }}/**
        fail_on_unmatched_files: true
        generate_release_notes: true # autogenerate the link to the version range diff
        body_path: ${{ env.RELEASE_NOTES_FILE }} # body will the appended to autogenerated content
        make_latest: true

  # builds the lichess-bot Docker image from the latest git tag & uploads it to Dockerhub
  build_docker:
    needs: bump_version
    runs-on: ubuntu-latest
    name: Update lichess-bot Docker image
    timeout-minutes: 20
    permissions:
      contents: read
    environment:
      name: lichess-bot-image
      url: ${{ steps.build_docker.outputs.url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6
      with:
        ref: ${{ needs.bump_version.outputs.docker_tag_url }}

    - uses: ./.github/actions/build_docker
      id: build_docker
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
        lichess_token: ${{ secrets.LICHESS_TOKEN }}
        tag_name: ${{ needs.bump_version.outputs.tag_name }}

  # stops the old Docker container, pulls the newly built image at the latest tag from Dockerhub,
  # and starts new container from this image
  deploy_vps:
    needs: [bump_version, build_docker]
    runs-on: ubuntu-latest
    name: Deploy Docker image to VPS
    timeout-minutes: 10
    permissions: {} # no permissions needed
    environment:
      name: vps
      url: https://cloud.digitalocean.com/droplets/517152619
    env:
      REMOTE_TAG: benvining/benbot-lichess:${{ needs.bump_version.outputs.tag_name }}
      IMAGE_NAME: benbot

    steps:
    - name: Update & restart Docker image
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1
      with:
        host: ${{ secrets.VPS_IP_V4 }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker stop ${{ env.IMAGE_NAME }}
          docker rm ${{ env.IMAGE_NAME }}
          docker pull ${{ env.REMOTE_TAG }}
          docker run -d --name ${{ env.IMAGE_NAME }} ${{ env.REMOTE_TAG }}
          docker image prune -a -f
